# Build starts faster without `sudo`
sudo: false

language: c
compiler: gcc
os: osx

cache:
  directories:
  - $HOME/.stack
  - $HOME/.local/bin
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/HaRe/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/core/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/haskell-lsp-types/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/cabal-helper/.stack-work
  - $TRAVIS_BUILD_DIR/hie-plugin-api/.stack-work
  timeout: 600

stages:
  - setup
  - dependencies
  - compile
  - test

env:
  - GHC_VER="8.4.3" ARGS="--stack-yaml=stack-8.4.3.yaml"

jobs:
   include:
     - stage: setup
       script:
         - mkdir -p $HOME/.stack
         - mkdir -p ~/.local/bin
         - |
           if [[ ! -f "${HOME}/.local/bin/stack" ]]
           then
             travis_retry curl -sSL https://www.stackage.org/stack/${TRAVIS_OS_NAME}-x86_64 \
               | tar xz --strip-components=1 -C ~/.local/bin --include   '*/stack'
           fi
         - travis_retry stack --no-terminal --install-ghc $ARGS setup

     - stage: dependencies
       script:
         - travis_retry stack --no-terminal --install-ghc $ARGS test --only-dependencies --no-run-tests

     - stage: compile
       script: stack --no-terminal $ARGS build --test --no-run-tests

     - stage: test
       script:
         - stack --no-terminal $ARGS exec hoogle generate
         - stack --no-terminal $ARGS test haskell-ide-engine:test:func-test
     -
       script:
         - stack --no-terminal $ARGS test haskell-ide-engine:test:dispatcher-test
         - stack --no-terminal $ARGS test haskell-ide-engine:test:unit-test
         - stack --no-terminal $ARGS test haskell-ide-engine:test:wrapper-test
