sudo: false
addons:
  apt:
    sources:
    - hvr-ghc
    - cassou-emacs
    packages:
    - python-virtualenv
    - libgmp-dev
    - emacs24-nox
cache:
  directories:
  - "$HOME/.stack/"
before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
- chmod a+x ~/.local/bin/stack
- stack --version
install:
- "./travis_long stack +RTS -N2 -RTS setup"
- "./travis_long stack build --only-snapshot"
script:
- "./travis_long stack +RTS -N1 -RTS build"
- "./travis_long stack +RTS -N1 -RTS build --test"
- "./travis_long stack exec emacs24 -- -q --batch -L elisp -l elisp/tests/hie-tests.el
  -f ert-run-tests-batch-and-exit"
- "./travis_long ./deploy-docs.sh"
notifications:
  irc:
    channels:
    - chat.freenode.net#haskell-ide-engine
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
    template:
    - "%{commit}: %{message} %{build_url}"
env:
  global:
  - GH_REF: github.com/haskell/haskell-ide-engine.git
  - secure: dU3Nf5iOYKOkrN3bX7XgtCAVf787NcSHkDV1sjHNovgPT7l8L7IPLknsdDnh2Yu7Hn7eTdn472ABgZaWJf6cKg/RLUmxD0QhOU1aW1hwjRi+BV1TsRT+0ikS3su35vv4rB3TL2Xo5aAIIHm1jGMDuAjQYzc+QHHMV6aRxJyHCjEYbUrUwW0ijLidZxZWMGleyjYsHtbBFOUrrJvcGU7dPX1MfH5g0+imCJBA14TxS+6C/O/AatvCxgQdV9mHNKwf2oYe/U3CHFm5a35vMQaDnkdc2qJ+H2qEq2syY78BYKjmF3wxFqICS/8Z0tiHMJ//xkEX16DmycaUukMOADsqUh+Ed1KhdMB8En6MnZbzoQQSFSyGbWa5wKYG7HAGoXabdvpcMk+7f8tIcu9n4F/AsFPicdcH86+PfVWlSPiCv4L7TgpFnCdUbwSD7NgvVtTCw35pF11hTtyNtS1m7/icNsbsm5Nb4KI4UpcAW8IyTug8b6EcY9RT8OHzJTg96plVSg4pUOLfaqrms7rOPc3UymrGyyJYg71IanLkWxPHenCx0aHVoTf54dnDqfdM0DzqJQ9lHyS57wZ/a5oha3sxI09L1bQE9RiYiqRrEFqMOcN7c5BvH05oYexldMp/CulfS5uzMvQd4yYDzMwF8OaY9ETF+VyaxOIBTcTs0a1Xp/M=
