sudo: false
language: c
os: osx
env:
- GHC_VER=8.4.3
- GHC_VER=8.2.1
cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  timeout: 800
before_install:
- mkdir -p ~/.local/bin
- travis_retry curl -sSL https://www.stackage.org/stack/${TRAVIS_OS_NAME}-x86_64 |
  tar xz --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack build --stack-yaml=stack-$GHC_VER.yaml
before_deploy:
- mv .stack-work/install/*/*/*/bin/hie hie-$GHC_VER
- mv .stack-work/install/*/*/8.4.3/bin/hie-wrapper hie-wrapper
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: jsRWOZVCLmI/pZzTwNfl7LPWMLIrpS44TmHQMw11hG6JV3JJWAiTBpxL5YI5kM/yvR67MTG5ocJdYm32SrJvuIyVbhoNuz9QyeAOc/QdALrQ9HPzFo26lKXT0qxZeBemBSa4O+gHp/X9qKzHQcsCPkgp+8l0pkUw9q+UFZMrC1LbTq3WpbXyqz7t0SKjkPRdAXUbY86xv/JY7PCioei2Ptm2m/CfuwLfQrN/PtsMnOlIKvVSPhaqh9fE3FT8xoMNXiE94V4ScVLDIr7fBNDhSPXufFm6BIGclC0fCncxW+Xe0fY+7M8SABoWyYaLl6MMzEReGvUZVCepvP7ES+fBaTSrMurU+F9v4lvIbbUFhZf6ko0hOigS2BxwgYdjnLOcVmIt6TExykMPbdEewszVNdoYZzgshhlVWEd5i9DG4l6v+RKvjm3S2scvKPzDtKmoIR0PCt+yXA89Q+lbeg7rZsrrGx9IsIKJvE8ZYXYMTSQzxEL49zPKTXYIudq0vETYonzrNa13xW41yiwWGLu5PCKNBu77wK4OoQaR6L8TluBg6BFurm4VjqCrCeexzFkvQSuazbK/UrLQskStS+F7tducUglpzFBJRA9SdMFL7yfmWagTqBfsFHeSki/wi1VrCpsX56YJNBQEXP0rclpkR3TUnwFUOTfBBvGT0JphjZc=
  file:
    - hie-$GHC_VER
    - hie-wrapper
  file_glob: true
  on:
    tags: true

