sudo: false
language: c
os: osx
env:
- GHC_VER=8.4.3
- GHC_VER=8.2.1
cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  timeout: 800
before_install:
- mkdir -p ~/.local/bin
- travis_retry curl -sSL https://www.stackage.org/stack/${TRAVIS_OS_NAME}-x86_64 |
  tar xz --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack build --stack-yaml=stack-$GHC_VER.yaml
before_deploy:
- mv .stack-work/install/*/*/*/bin/hie hie-$GHC_VER
- mv .stack-work/install/*/*/8.4.3/bin/hie-wrapper hie-wrapper
deploy:
  provider: releases
  api_key:
    secure: hN1dcT2bnhPClsnccE7GUdJk+9gpwLNAF5S+KoT/5Np39y91dcoOm9L1W0odWpIRmEmnCF2x4Evf91uhPyGo1ZKGMFlD8i87jwAgLtsME5Vvj+O9c2URpSc6xBiCIpB5SThdAr7lMfuvM6/M5niTfGUNkw/vTtkwf2XhrV0X2n5fFmNh8fmdy5YDWZjgW06o8qLCAQTnVIBAlRJqmx1tTw2lyNmoo/d8sFc5PY8mK1Nvn3d+ZFR6Z35FJM37I7dod8Od5XKTSwtIa7KbiaC3tGRQIf58NRAPQW5Nn+XVkc/Z0Oc9oZM0jragOAnEEo4YK1GNHNOI07Y48CbGqQNauUg4eLMnQ0ro2zPbMchciqfBdUJR+3O6zZ3gkgyou/tsQkFSWLWAHpjrhuFA6Az8YClhRMPxjQwb3quxOCDD6O+nBHcGZgOCIm5DuLfCmEtrOjp0Rk+kVbESIe2eQD5ubMBPkWqItquadSW0OicQ/e+rCK/PFP9H1T9nnglMx+5nHCiBBDdWZtV15kvUOq5D9Ac0UIn8YWcMOzgrentL0eoBDntLNefAV3ahtxqlTDdvny+vtevdM2vUW9faBusOBoot2vWnhM5qZ0ta0t5j2wRBrfdP4YnFqzNOha2h7p8fEgWhz+S2S/RlCmFftS7HViO2eAX3FVqVGyyMKnZsdg0=
  skip_cleanup: true
  file:
    - hie-$GHC_VER
    - hie-wrapper
  file_glob: true
  on:
    repo: bubba/haskell-ide-engine
    tags: true
