resolver: nightly-2017-06-14
packages:
- .
- hie-apply-refact
- hie-base
- hie-docs-generator
- hie-eg-plugin-async
- hie-example-plugin2
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-hoogle
- hie-plugin-api
- hie-brittany
# - ../haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: bfa74634a83b3595346c785c52271edd32e84cf9
  extra-dep: true
- location:
    git: https://github.com/alanz/ghc-dump-tree.git
    commit: 9dbca928ad5507b144f46bb95123a08d24f24808
  extra-dep: true
# - location:
#     git: https://github.com/sol/hspec-jenkins.git
#     commit: cb012b23c4e524dde9ea129b6146dda20a5ca505
#   extra-dep: true
# - ../HaRe
- location:
    git: https://github.com/alanz/HaRe.git
    commit: b5f84fe11bd097956c2d2f1680fb08f0174799b7
  extra-dep: true
# - ../../DanielG/ghc-mod
# - ../ghc-mod
- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 6d78f17e655bd545576b8ef02fd65a653dc72a98
  extra-dep: true
- location:
    git: https://github.com/lspitzner/brittany.git
    commit: 16f5aa118d707cc484cdee39351b176b6d17c3df
  extra-dep: true

extra-deps:
- apply-refact-0.3.0.1
# - apply-refact-0.4.0.0
- butcher-1.1.0.0
- czipwith-1.0.0.0
- data-tree-print-0.1.0.0
- deque-0.2
- monad-memo-0.4.1
- pipes-aeson-0.4.1.8
- pipes-network-0.6.4.1
# - hspec-jenkins-0.1.1
flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-base:
    pedantic: true
  hie-docs-generator:
    pedantic: true
  hie-eg-plugin-async:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-ghc-tree:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true
  hie-brittany:
    pedantic: true
