#resolver: lts-3.11
# Nightly has ghc-mod/cabal-helper, not in lts yet
resolver: nightly-2015-12-02
packages:
- .
- hie-example-plugin2
- hie-plugin-api
- hie-ghc-mod
- hie-hare
extra-deps:
 - HaRe-0.8.2.1
 - rosezipper-0.2
 - syz-0.2.0.0
