# resolver: nightly-2017-02-08
# resolver: nightly-2017-03-07
# resolver: nightly-2017-03-17
# resolver: nightly-2017-03-20
resolver: nightly-2017-04-02
packages:
- .
- hie-apply-refact
- hie-base
- hie-example-plugin2
- hie-eg-plugin-async
- hie-plugin-api
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-docs-generator
# - ../haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: 509b06ac04f93f607414719716406c8fe205157a
  extra-dep: true
- location:
    git: https://github.com/alanz/ghc-dump-tree.git
    commit: 9dbca928ad5507b144f46bb95123a08d24f24808
  extra-dep: true
# - location:
#     git: https://github.com/sol/hspec-jenkins.git
#     commit: cb012b23c4e524dde9ea129b6146dda20a5ca505
#   extra-dep: true
# - location:
#     git: https://github.com/alanz/HaRe.git
#     # git: https://github.com/RefactoringTools/HaRe.git
#     commit: ea029eb3ecab66b848e7ac9afbf5f377464cabc6
#   extra-dep: true
extra-deps:
- apply-refact-0.3.0.1
- pipes-aeson-0.4.1.8
- pipes-network-0.6.4.1
# - hspec-jenkins-0.1.1
