resolver: nightly-2018-04-24 # GHC 8.4.2
packages:
- .
- hie-plugin-api

- location:
    ./submodules/HaRe
  extra-dep: true

- location:
    ./submodules/brittany
  extra-dep: true

- location:
    ./submodules/cabal-helper
  extra-dep: true

- location:
    ./submodules/ghc-mod
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    ./submodules/haskell-lsp
  extra-dep: true
  subdirs:
    - .
    - haskell-lsp-types

- location:
    ./submodules/yi-rope
  extra-dep: true

extra-deps:
- apply-refact-0.5.0.0
- constrained-dynamic-0.1.0.0
- haddock-api-2.19.0.1
- sorted-list-0.2.1.0
- syz-0.2.0.0


flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
