# resolver: nightly-2017-04-02
resolver: nightly-2017-04-28
packages:
- .
- hie-apply-refact
- hie-base
- hie-example-plugin2
- hie-eg-plugin-async
- hie-plugin-api
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-hoogle
- hie-docs-generator
# - ../haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: f1a23711257f23fed81f206d2a008ff58458aee9
  extra-dep: true
- location:
    git: https://github.com/alanz/ghc-dump-tree.git
    commit: 9dbca928ad5507b144f46bb95123a08d24f24808
  extra-dep: true
# - location:
#     git: https://github.com/sol/hspec-jenkins.git
#     commit: cb012b23c4e524dde9ea129b6146dda20a5ca505
#   extra-dep: true
# - ../HaRe
- location:
    git: https://github.com/alanz/HaRe.git
    # git: https://github.com/RefactoringTools/HaRe.git
    commit: 423bc0b235dc7ede961278f6e614813b851bfd0a
  extra-dep: true
# - ../../DanielG/ghc-mod
- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 657d6826278027c769bb43de6c340f95f4e0241d
  extra-dep: true
- location:
    git: https://github.com/wz1000/hoogle.git
    commit: d522d7f406ff26b8df4601182e1b7ccd1a7162ad
  extra-dep: true
extra-deps:
- apply-refact-0.3.0.1
- pipes-aeson-0.4.1.8
- pipes-network-0.6.4.1
# - hspec-jenkins-0.1.1
