resolver: nightly-2017-06-16
packages:
- .
- hie-apply-refact
- hie-base
- hie-build-plugin
- hie-eg-plugin-async
- hie-example-plugin2
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-hoogle
- hie-plugin-api
- hie-brittany
- hie-haddock

# - ../haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: fe2289c6cd16620bb93aacd263aadb59a01f2ca7
  extra-dep: true

- location:
    git: https://github.com/edsko/ghc-dump-tree.git
    commit: 50f8b28fda675cca4df53909667c740120060c49
  extra-dep: true

# - ../HaRe
- location:
    git: https://github.com/alanz/HaRe.git
    commit: e325975450ce89d790ed3f92de3ef675967d9538
  extra-dep: true

- location:
    git: https://github.com/alanz/ghc-mod.git
    commit:  f780d9568a3bbe5d9bdd01a19ad56951d1616640
    # ../ghc-mod
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    # ../cabal-helper
    # git: https://github.com/alanz/cabal-helper.git
    # commit: 4cbbaac564aa336ffa0cb0de1ba26a962367199f
    git: https://github.com/DanielG/cabal-helper.git
    commit: 4af5dddb8a881572bb6622430dc4c45ec02701df
  extra-dep: true

- location:
    git: https://github.com/alanz/brittany.git
    # commit: baac0a6a7e74ea70cae02c4d317e4a24bce8e9b8
    commit: 32a193f0ce02ec36a6032852454db96573ab3a60
  extra-dep: true

# - location:
#     git: https://github.com/haskell/haddock.git
#     commit:  fe4c6c7d2907a79118d836e72c0442d666091524
#   extra-dep: true
#   subdirs:
#     - haddock-api
#     - haddock-library

extra-deps:
- apply-refact-0.3.0.1
- butcher-1.1.0.1
# - Cabal-2.0.0.2
- czipwith-1.0.0.0
- data-tree-print-0.1.0.0
- deque-0.2
- hoogle-5.0.13
- monad-memo-0.4.1
- syz-0.2.0.0
- yi-rope-0.10

flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-base:
    pedantic: true
  hie-eg-plugin-async:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-ghc-tree:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true
  hie-brittany:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
