resolver: nightly-2016-02-03
packages:
- .
- hie-apply-refact
- hie-base
- hie-build-plugin
- hie-example-plugin2
- hie-eg-plugin-async
- hie-plugin-api
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
extra-deps:
  - ghc-dump-tree-0.2.0.0
  - ghc-7.10.3
