resolver: nightly-2019-07-07 # GHC 8.6.5
packages:
- .
- hie-plugin-api
- hie-bios

extra-deps:
- ./submodules/HaRe
- ./submodules/cabal-helper
- ./submodules/ghc-mod/ghc-project-types

- ansi-terminal-0.8.2
- butcher-1.3.2.1
- bytestring-trie-0.2.5.0
- ansi-wl-pprint-0.6.8.2
- brittany-0.12.0.0
- cabal-plan-0.4.0.0
- constrained-dynamic-0.1.0.0
- floskell-0.10.1
- ghc-lib-parser-8.8.0.20190424
- haddock-api-2.22.0
- haskell-lsp-0.15.0.0
- haskell-lsp-types-0.15.0.0
- hlint-2.2
- hsimport-0.10.0
- lsp-test-0.6.0.0
- monad-dijkstra-0.1.1.2@rev:1
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32
- dhall-1.20.1@sha256:3377090039ba3560b50515799affc57d74d2d3e57d3f8699bb2a9fc428fa4918,23401


# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
