# resolver: nightly-2016-08-06
resolver: nightly-2016-08-25
packages:
- .
- hie-apply-refact
- hie-base
- hie-example-plugin2
- hie-eg-plugin-async
- hie-plugin-api
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-docs-generator
extra-deps:
  - ghc-dump-tree-0.2.0.1
  # - ghc-7.10.3
