#resolver: lts-3.11
# Nightly has ghc-mod/cabal-helper, not in lts yet
resolver: nightly-2015-12-02
packages:
- .
- hie-example-plugin2
- hie-plugin-api
- hie-ghc-mod
- hie-hare
# - ../ghci-ng
- location:
    git: https://github.com/kazu-yamamoto/ghc-mod.git
    commit: b9bd4ebf77b22d2d9061d647d7799ddcc7c51228
    # commit: bff86be69f556f80a8dcd9dd42774ab77cb00eba
  extra-dep: true
- location:
    git: git@github.com:dmjio/servant-swagger.git
    commit: 3247f3019ec81b580a795695d3d4417c2f663fb7
extra-deps:
 - HaRe-0.8.2.1
 - rosezipper-0.2
 - syz-0.2.0.0
