#resolver: lts-3.11
# Nightly has ghc-mod/cabal-helper, not in lts yet
resolver: nightly-2015-12-02
packages:
- .
- hie-example-plugin2
- hie-plugin-api
- hie-ghc-mod
- hie-hare
# - ../ghci-ng
- location:
    git: https://github.com/kazu-yamamoto/ghc-mod.git
    commit: bff86be69f556f80a8dcd9dd42774ab77cb00eba
  extra-dep: true
extra-deps:
 - HaRe-0.8.2.1
 - rosezipper-0.2
 - syz-0.2.0.0
