resolver: nightly-2018-01-15
# resolver: nightly-2017-12-15
packages:
- .
- hie-apply-refact
- hie-brittany
- hie-build-plugin
- hie-example-plugin2
- hie-ghc-mod
- hie-haddock
- hie-hare
- hie-hoogle
- hie-plugin-api

- location:
    git: https://gitlab.com/alanz/HaRe.git
    commit: e325975450ce89d790ed3f92de3ef675967d9538
  extra-dep: true

- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 47e200a728a575f407ee6f9893d9a1e77b1b5325
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    git: https://gitlab.com/alanz/cabal-helper.git
    commit: f53a39b7fac201d9ac2baae709b977546e448baf
  extra-dep: true

extra-deps:
- constrained-dynamic-0.1.0.0
- haddock-api-2.18.1
- haddock-library-1.4.4
- syz-0.2.0.0

flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-brittany:
    pedantic: true
  hie-build-plugin:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-haddock:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
