# resolver: nightly-2016-09-04
resolver: nightly-2017-01-13
packages:
- .
- hie-apply-refact
- hie-base
- hie-example-plugin2
- hie-eg-plugin-async
- hie-plugin-api
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-docs-generator
# - ../haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: 1efc4a2dce05f91b12c97a54827216c8f7c422db
  extra-dep: true
- location:
    git: https://github.com/alanz/HaRe.git
    # git: https://github.com/RefactoringTools/HaRe.git
    commit: 5551c66f586c1ddf38174bcd879aa324d0c9da7a
  extra-dep: true
- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 358465511840bae3ff771572586d65dd12fec3bd
  extra-dep: true
- location:
    git: https://github.com/alanz/pipes-network.git
    commit: 5647903585510a921fbff96cbfc38d8ba367610f
  extra-dep: true
- location:
    git: https://github.com/alanz/pipes-attoparsec.git
    commit: 50485db84313e7620194f0d16e5f0c1cf57f11e8
  extra-dep: true
- location:
    git: https://github.com/alanz/pipes-aeson.git
    commit: 9ff8342b8be905603ff9a3101d7b7e377e0c8d6b
  extra-dep: true
extra-deps:
- apply-refact-0.3.0.1
- cabal-helper-0.7.2.0
- ghc-dump-tree-0.2.0.2
