resolver: nightly-2017-06-12
packages:
- .
- hie-apply-refact
- hie-base
- hie-docs-generator
- hie-eg-plugin-async
- hie-example-plugin2
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-hoogle
- hie-plugin-api
#- haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: 258d3cc92a9f61f7fab92a29404492b1fdfa83b2
  extra-dep: true
- location:
    git: https://github.com/alanz/ghc-dump-tree.git
    commit: 9dbca928ad5507b144f46bb95123a08d24f24808
  extra-dep: true
# - location:
#     git: https://github.com/sol/hspec-jenkins.git
#     commit: cb012b23c4e524dde9ea129b6146dda20a5ca505
#   extra-dep: true
# - ../HaRe
# - location:
#     git: https://github.com/alanz/HaRe.git
#     # git: https://github.com/RefactoringTools/HaRe.git
#     # commit: 423bc0b235dc7ede961278f6e614813b851bfd0a
#     commit: df7c1def6156f6179a41b9053509eb5af13ef4a3
#   extra-dep: true
# - ../../DanielG/ghc-mod
# - ../ghc-mod
- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 36fbe25e07c34ba81fbba735d4046a98ae75db3a
  extra-dep: true
# - ../hlint
- location:
    git: https://github.com/alanz/hlint.git
    commit: 1c78d5178128a67766db3c62c22bae24138f335a
  extra-dep: true
extra-deps:
- apply-refact-0.3.0.1
- pipes-aeson-0.4.1.8
- pipes-network-0.6.4.1
# - hspec-jenkins-0.1.1
flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-base:
    pedantic: true
  hie-docs-generator:
    pedantic: true
  hie-eg-plugin-async:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-ghc-tree:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true
