resolver: nightly-2019-04-30 # First GHC 8.6.5
packages:
- .
- hie-plugin-api
- hie-bios

extra-deps:
- ./submodules/HaRe
- ./submodules/brittany
- ./submodules/cabal-helper
- ./submodules/ghc-mod/ghc-project-types

- ansi-terminal-0.8.2
- butcher-1.3.2.1
- bytestring-trie-0.2.5.0
- cabal-plan-0.4.0.0
- constrained-dynamic-0.1.0.0
- deque-0.2.7
- floskell-0.10.0
- ghc-exactprint-0.5.8.2
- ghc-lib-parser-0.20190523
- haddock-api-2.22.0
- haskell-lsp-0.13.0.0
- haskell-lsp-types-0.13.0.0
- hlint-2.1.22
- hsimport-0.10.0
- lsp-test-0.5.2.3
- monad-dijkstra-0.1.1.2@rev:1
- monad-memo-0.4.1
- multistate-0.8.0.1
- rope-utf16-splay-0.3.1.0
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32
- dhall-1.20.1@sha256:3377090039ba3560b50515799affc57d74d2d3e57d3f8699bb2a9fc428fa4918,23401


# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
