resolver: nightly-2018-04-24 # GHC 8.4.2
packages:
- .
- hie-plugin-api

- location:
    ./submodules/HaRe
  extra-dep: true

- location:
    ./submodules/ghc-mod
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    ./submodules/cabal-helper
  extra-dep: true

- location:
    ./submodules/yi-rope
  extra-dep: true

- location:
    ./submodules/sorted-list
  extra-dep: true

- location:
    ./submodules/haskell-lsp
  extra-dep: true

extra-deps:
- apply-refact-0.5.0.0
- constrained-dynamic-0.1.0.0
- haddock-api-2.19.0.1
- syz-0.2.0.0

# -------------------------------------------------------
# - cabal new-configure:
#
# Build profile: -w ghc-8.4.2 -O1
# In order, the following would be built (use -v for more details):
#  - Diff-0.3.4 (lib) (requires build)
#  - Glob-0.9.2 (lib) (requires download & build)
#  - Only-0.1 (lib) (requires download & build)
#  - Strafunski-StrategyLib-5.0.1.0 (lib) (requires build)
#  - abstract-deque-0.3 (lib) (requires download & build)
#  - abstract-par-0.3.3 (lib) (requires download & build)
#  - appar-0.1.4 (requires build)
#  - async-2.2.1 (lib) (requires build)
#  - auto-update-0.1.4 (lib) (requires build)
#  - base-compat-batteries-0.10.1 (lib) (requires download & build)
#  - base-prelude-1.2.0.1 (lib) (requires build)
#  - base16-bytestring-0.1.1.6 (requires build)
#  - base64-bytestring-1.0.0.1 (lib) (requires build)
#  - basement-0.0.7 (lib) (requires build)
#  - blaze-builder-0.4.1.0 (lib) (requires build)
#  - byteable-0.1.1 (lib) (requires build)
#  - byteorder-1.0.4 (requires build)
#  - bytestring-builder-0.10.8.1.0 (lib) (requires build)
#  - cabal-helper-0.8.0.3 (lib) (first run)
#  - cereal-0.5.5.0 (lib) (requires build)
#  - constrained-dynamic-0.1.0.0 (lib) (requires build)
#  - cookie-0.4.4 (lib) (requires build)
#  - cryptohash-sha256-0.11.101.0 (lib) (requires build)
#  - doctest-0.15.0 (exe:doctest) (requires build)
#  - easy-file-0.2.1 (requires build)
#  - echo-0.1.3 (lib) (requires build)
#  - ed25519-0.0.5.0 (lib) (requires build)
#  - edit-distance-0.2.2.1 (lib) (requires build)
#  - ekg-core-0.1.1.4 (lib) (requires build)
#  - erf-2.0.0.0 (requires download & build)
#  - filemanip-0.3.6.3 (requires build)
#  - fmlist-0.9.2 (lib) (requires build)
#  - free-5.0.1 (lib) (requires build)
#  - generic-deriving-1.12.1 (lib) (requires build)
#  - gitrev-1.3.1 (lib) (requires build)
#  - haddock-library-1.5.0.1 (lib:attoparsec) (requires download & build)
#  - hlint-2.1.3 (exe:hlint) (requires build)
#  - hostname-1.0 (requires build)
#  - hourglass-0.2.11 (lib) (requires build)
#  - hslogger-1.2.10 (lib) (requires build)
#  - hspec-discover-2.5.0 (exe:hspec-discover) (requires build)
#  - http-date-0.0.7 (lib) (requires download & build)
#  - http-types-0.12.1 (lib) (requires build)
#  - js-flot-0.8.3 (lib) (requires build)
#  - js-jquery-3.3.1 (lib) (requires build)
#  - lifted-base-0.2.3.12 (lib) (requires build)
#  - managed-1.0.6 (lib) (requires build)
#  - microstache-1.0.1.1 (lib) (requires download & build)
#  - mime-types-0.1.0.7 (lib) (requires build)
#  - mmap-0.5.9 (requires build)
#  - network-uri-2.6.1.0 (lib) (requires build)
#  - optional-args-1.0.2 (lib) (requires build)
#  - primes-0.2.1.0 (requires build)
#  - psqueues-0.2.6.0 (lib) (requires build)
#  - readable-0.3.1 (requires build)
#  - regex-base-0.93.2 (requires build)
#  - simple-sendfile-0.2.27 (lib) (requires build)
#  - sorted-list-0.2.0.0 (lib) (first run)
#  - system-filepath-0.4.14 (requires build)
#  - syz-0.2.0.0 (requires build)
#  - tagsoup-0.14.6 (lib) (requires build)
#  - tar-0.5.1.0 (lib) (requires build)
#  - text-short-0.1.2 (lib) (requires download & build)
#  - unix-time-0.3.8 (requires build)
#  - utility-ht-0.0.14 (lib) (requires build)
#  - vault-0.3.1.0 (requires build)
#  - vector-binary-instances-0.2.4 (lib) (requires download & build)
#  - vector-th-unbox-0.2.1.6 (lib) (requires build)
#  - word8-0.1.3 (lib) (requires build)
#  - yi-rope-0.10 (lib) (first run)
#  - zlib-0.6.2 (lib) (requires build)
#  - typed-process-0.2.2.0 (lib) (requires build)
#  - vector-builder-0.3.4.1 (lib) (requires build)
#  - conversion-1.2.1 (lib) (requires build)
#  - resolv-0.1.1.1 (requires build)
#  - foundation-0.0.20 (lib) (requires build)
#  - iproute-1.7.4 (lib) (requires download & build)
#  - bsb-http-chunked-0.0.0.2 (lib) (requires build)
#  - ghc-mod-core-5.9.0.0 (lib) (first run)
#  - socks-0.5.6 (lib) (requires build)
#  - monad-par-extras-0.3.3 (lib) (requires download & build)
#  - ekg-json-0.1.0.6 (lib) (requires build)
#  - ListLike-4.6 (lib) (requires build)
#  - ghc-exactprint-0.5.6.1 (lib) (requires build)
#  - adjunctions-4.4 (lib) (requires build)
#  - optparse-simple-0.1.0 (lib) (requires build)
#  - haddock-library-1.5.0.1 (lib) (requires download & build)
#  - HTTP-4000.3.11 (lib) (requires build)
#  - monoid-subclasses-0.4.6 (lib) (requires build)
#  - http2-1.6.3 (lib) (requires build)
#  - regex-posix-0.95.2 (requires build)
#  - system-fileio-0.3.16.3 (lib) (requires build)
#  - cassava-0.5.1.0 (lib) (requires download & build)
#  - fast-logger-2.4.11 (lib) (requires build)
#  - storable-record-0.0.4 (requires build)
#  - wai-3.2.1.2 (lib) (requires build)
#  - math-functions-0.2.1.0 (lib) (requires build)
#  - yi-rope-0.10 (test:spec) (first run)
#  - zlib-bindings-0.1.1.5 (lib) (requires build)
#  - streaming-commons-0.2.0.0 (lib) (requires build)
#  - hackage-security-0.5.3.0 (lib) (requires build)
#  - conversion-case-insensitive-1.0.0.0 (lib) (requires build)
#  - conversion-bytestring-1.0.1 (lib) (requires build)
#  - memory-0.14.16 (lib) (requires build)
#  - ghc-mod-5.9.0.0 (first run)
#  - process-extras-0.7.4 (lib) (requires build)
#  - apply-refact-0.5.0.0 (lib) (requires download & build)
#  - apply-refact-0.5.0.0 (exe:refactor) (requires download & build)
#  - HaRe-0.8.4.1 (lib) (first run)
#  - kan-extensions-5.1 (requires build)
#  - haddock-api-2.19.0.1 (lib) (requires download & build)
#  - storable-tuple-0.0.3.3 (requires build)
#  - wai-logger-2.3.2 (lib) (requires build)
#  - mwc-random-0.13.6.0 (lib) (requires build)
#  - io-streams-1.5.0.1 (lib) (requires build)
#  - warp-3.2.19 (lib) (requires download & build)
#  - conduit-extra-1.3.0 (lib) (requires build)
#  - cabal-install-2.2.0.0 (requires build)
#  - conversion-text-1.0.1 (lib) (requires build)
#  - pem-0.2.4 (lib) (requires build)
#  - http-client-0.5.12.1 (lib) (requires download & build)
#  - cryptonite-0.25 (lib) (requires build)
#  - asn1-types-0.3.2 (requires build)
#  - HaRe-0.8.4.1 (exe:ghc-hare) (first run)
#  - lens-4.16.1 (requires build)
#  - monad-par-0.3.4.8 (lib) (requires download & build)
#  - foldl-1.4.0 (lib) (requires build)
#  - snap-core-1.0.3.2 (lib) (requires build)
#  - io-streams-haproxy-1.0.0.2 (lib) (requires build)
#  - cabal-helper-0.8.0.3 (test:ghc-session) (first run)
#  - cabal-helper-0.8.0.3 (test:compile-test) (first run)
#  - cabal-helper-0.8.0.3 (exe:cabal-helper-wrapper) (first run)
#  - asn1-encoding-0.9.5 (lib) (requires build)
#  - haskell-lsp-0.2.0.1 (lib) (first run)
#  - statistics-0.14.0.2 (lib) (requires download & build)
#  - turtle-1.5.8 (lib) (requires build)
#  - snap-server-1.1.0.0 (lib) (requires build)
#  - asn1-parse-0.9.4 (requires build)
#  - hie-plugin-api-0.1.0.0 (lib) (first run)
#  - haskell-lsp-0.2.0.1 (exe:lsp-hello) (first run)
#  - haskell-lsp-0.2.0.1 (test:haskell-lsp-test) (first run)
#  - criterion-1.4.1.0 (lib) (requires download & build)
#  - HaRe-0.8.4.1 (test:spec) (first run)
#  - ekg-0.4.0.15 (lib) (requires build)
#  - x509-1.7.3 (lib) (requires build)
#  - yi-rope-0.10 (bench:bench) (first run)
#  - sorted-list-0.2.0.0 (bench:sorted-list-map-bench) (first run)
#  - criterion-1.4.1.0 (exe:criterion-report) (requires download & build)
#  - x509-store-1.6.6 (lib) (requires build)
#  - x509-validation-1.6.10 (lib) (requires build)
#  - x509-system-1.6.6 (lib) (requires build)
#  - tls-1.4.1 (lib) (requires build)
#  - tls-session-manager-0.0.0.2 (lib) (requires build)
#  - connection-0.2.8 (requires build)
#  - warp-tls-3.2.4.3 (requires download & build)
#  - http-client-tls-0.3.5.3 (lib) (requires build)
#  - http-conduit-2.3.1 (lib) (requires build)
#  - hoogle-5.0.17.3 (lib) (requires download & build)
#  - hoogle-5.0.17.3 (exe:hoogle) (requires download & build)
#  - haskell-ide-engine-0.1.0.0 (lib) (first run)
#  - haskell-ide-engine-0.1.0.0 (exe:hie) (first run)
#  - haskell-ide-engine-0.1.0.0 (test:haskell-ide-test) (first run)
#  - haskell-ide-engine-0.1.0.0 (test:haskell-ide-func-test) (first run)


flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
