resolver: nightly-2018-01-15
# resolver: nightly-2017-12-15
packages:
- .
- hie-apply-refact
- hie-base
- hie-brittany
- hie-build-plugin
- hie-example-plugin2
- hie-ghc-mod
- hie-haddock
- hie-hare
- hie-hoogle
- hie-plugin-api

- location:
    git: https://gitlab.com/alanz/HaRe.git
    commit: e325975450ce89d790ed3f92de3ef675967d9538
  extra-dep: true

- location:
    # ../ghc-mod
    git: https://github.com/wz1000/ghc-mod.git
    commit: a2beda19b6d1975be7bed1081069ed0e42fa39e9
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    git: https://gitlab.com/dxld/cabal-helper.git
    commit: 4bfc6b916fcc696a5d82e7cd35713d6eabcb0533
  extra-dep: true

extra-deps:
- constrained-dynamic-0.1.0.0
- haddock-api-2.18.1
- haddock-library-1.4.4
- syz-0.2.0.0
- unix-compat-0.4.3.1

flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-base:
    pedantic: true
  hie-brittany:
    pedantic: true
  hie-build-plugin:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-haddock:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
