resolver: lts-12.17 # GHC 8.4.4
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/brittany
- ./submodules/HaRe
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core
- ./submodules/cabal-helper

- base-compat-0.9.3
- base-orphans-0.7
# - brittany-0.11.0.0
- cabal-plan-0.3.0.0
- constrained-dynamic-0.1.0.0
- ghc-exactprint-0.5.8.2
- haddock-api-2.20.0
- haddock-library-1.6.0
- haskell-lsp-0.8.0.1
- haskell-lsp-types-0.8.0.1
- hsimport-0.8.6
- lsp-test-0.4.0.0
- monad-memo-0.4.1
- pretty-show-1.8.2
- semigroupoids-5.2.2
- syz-0.2.0.0
- temporary-1.2.1.1

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
