resolver: nightly-2016-01-14
packages:
- .
- hie-apply-refact
- hie-base
- hie-example-plugin2
- hie-eg-plugin-async
- hie-plugin-api
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-docs-generator
- hie-ide-backend
- location:
    git: https://github.com/mpickering/apply-refact.git
    commit: 402458652844c1a0f42b15123e0ceff761919415
  extra-dep: true
- location:
    git: https://github.com/DanielG/ghc-mod.git
    commit: 54fe4a0edbdddfbdc2acc43edde2b061ca5b399b
  extra-dep: true
- location:
    git: https://github.com/cocreature/HaRe.git
    commit: 318841c2c125de60a4db9de75d108841651db410
  extra-dep: true
extra-deps:
  - ghc-dump-tree-0.2.0.0
