resolver: nightly-2018-04-24 # GHC 8.4.2
packages:
- .
- hie-plugin-api

- location:
    ./submodules/HaRe
  extra-dep: true

- location:
    ./submodules/ghc-mod
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    ./submodules/cabal-helper
  extra-dep: true

extra-deps:
- brittany-0.10.0.0
- Cabal-2.0.1.1
- apply-refact-0.5.0.0
- constrained-dynamic-0.1.0.0
- czipwith-1.0.0.0
- djinn-ghc-0.0.2.3
- ghc-8.2.2
- ghc-boot-th-8.2.2
- ghc-syb-utils-0.2.3.3
- haddock-api-2.19.0.1
- haskell-lsp-0.2.0.1
- hspec-2.4.8
- multistate-0.7.1.2
- optparse-applicative-0.13.2.0
- sorted-list-0.2.0.0
- syz-0.2.0.0
- yi-rope-0.10

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
