resolver: lts-11.2
packages:
- .
- hie-plugin-api

- location:
    git: https://gitlab.com/alanz/HaRe.git
    commit: e325975450ce89d790ed3f92de3ef675967d9538
  extra-dep: true

- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 47e200a728a575f407ee6f9893d9a1e77b1b5325
  extra-dep: true
  subdirs:
    - .
    - core

extra-deps:
- brittany-0.10.0.0
- cabal-helper-0.8.0.2
- constrained-dynamic-0.1.0.0
- haddock-api-2.18.1
- haddock-library-1.4.4
- syz-0.2.0.0

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
