resolver: nightly-2017-02-08
packages:
- .
- hie-apply-refact
- hie-base
- hie-example-plugin2
- hie-eg-plugin-async
- hie-plugin-api
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-docs-generator
# - ../haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: 1efc4a2dce05f91b12c97a54827216c8f7c422db
  extra-dep: true
- location:
    git: https://github.com/alanz/HaRe.git
    # git: https://github.com/RefactoringTools/HaRe.git
    commit: ea029eb3ecab66b848e7ac9afbf5f377464cabc6
  extra-dep: true
extra-deps:
- apply-refact-0.3.0.1
- ghc-dump-tree-0.2.0.2
- ghc-exactprint-0.5.3.0
- pipes-aeson-0.4.1.7
- pipes-network-0.6.4.1
