resolver: nightly-2017-09-10
packages:
- .
- hie-apply-refact
- hie-base
- hie-build-plugin
- hie-eg-plugin-async
- hie-example-plugin2
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-hoogle
- hie-plugin-api
- hie-brittany

# - ../haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: fe2289c6cd16620bb93aacd263aadb59a01f2ca7
  extra-dep: true

- location:
    git: https://github.com/robrix/ghc-dump-tree.git
    commit: 2e3dc742e6a701f3b9615a3d5a7d0dbc02cd60d4
  extra-dep: true

# - ../HaRe
- location:
    git: https://github.com/alanz/HaRe.git
    commit: e325975450ce89d790ed3f92de3ef675967d9538
  extra-dep: true

# - ../ghc-mod
# - ../ghc-mod/ghc-mod-core
- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 9056aa81af3cf08c574524d1b19d29c93fd00016
  extra-dep: true
  subdirs:
    - .
    - ghc-mod-core

- location:
    git: https://github.com/joshvera/cabal-helper.git
    commit: 8191a72351fb3d622576597ae965bea97fc4147e
  extra-dep: true

- location:
    git: https://github.com/alanz/brittany.git
    # commit: baac0a6a7e74ea70cae02c4d317e4a24bce8e9b8
    commit: 32a193f0ce02ec36a6032852454db96573ab3a60
  extra-dep: true

extra-deps:
# - apply-refact-0.4.0.1
- butcher-1.1.0.1
- czipwith-1.0.0.0
- data-tree-print-0.1.0.0
- deque-0.2
- monad-memo-0.4.1
- hoogle-5.0.13
- syz-0.2.0.0
- brittany-0.8.0.2
- yi-rope-0.10
flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-base:
    pedantic: true
  hie-eg-plugin-async:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-ghc-tree:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true
  hie-brittany:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
