jobs:
- job: Windows_installhs_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  variables:
    YAML_FILE: install/shake.yaml
    STACK_ROOT: "D:\\sr"
  steps:
  - task: Cache@2
    inputs:
      key: '"stack" | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(YAML_FILE) | $(Build.SourcesDirectory)/install/shake.yaml'
      path: .azure-cache
      cacheHitVar: CACHE_RESTORED
    displayName: "Cache stack-root"
  - bash: |
      mkdir -p "$STACK_ROOT"
      tar -vxzf .azure-cache/stack-root.tar.gz -C /d
      mkdir -p .stack-work
      tar -vxzf .azure-cache/stack-work.tar.gz
      mkdir -p ./install/.stack-work
      tar -vxzf .azure-cache/install-stack-work.tar.gz
    displayName: "Unpack cache"
    condition: eq(variables.CACHE_RESTORED, 'true')
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      mkdir -p "$STACK_ROOT"
      echo "local-programs-path: D:/bin/stack" > "$STACK_ROOT/config.yaml"
    displayName: Install stack
  - bash: |
      source .azure/windows-stack.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/windows-stack.bashrc
      stack --stack-yaml $(YAML_FILE) build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/windows-stack.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie-install`
  - bash: |
      source .azure/windows-stack.bashrc
      stack install.hs help
    displayName: Run help of `install.hs`
  - bash: |
      source .azure/windows-stack.bashrc
      # Some executions fails with spurious errors installing executables
      stack install.hs latest || stack install.hs latest
    displayName: Run latest target of `install.hs`
  - bash: |
      mkdir -p .azure-cache
      tar -vczf .azure-cache/stack-root.tar.gz $(cygpath $STACK_ROOT)
      tar -vczf .azure-cache/stack-work.tar.gz .stack-work
      tar -vczf .azure-cache/install-stack-work.tar.gz ./install/.stack-work
    displayName: "Pack cache"
