jobs:
- job: Windows_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      stack-def:
        YAML_FILE: stack.yaml
      stack-8.6.5:
        YAML_FILE: stack-8.6.5.yaml
      stack-8.6.4:
        YAML_FILE: stack-8.6.4.yaml
      stack-8.6.2:
        YAML_FILE: stack-8.6.2.yaml
      stack-8.6.1:
        YAML_FILE: stack-8.6.1.yaml
      stack-8.4.4:
        YAML_FILE: stack-8.4.4.yaml
      stack-8.4.3:
        YAML_FILE: stack-8.4.3.yaml
      stack-8.4.2:
        YAML_FILE: stack-8.4.2.yaml
      stack-8.2.2:
        YAML_FILE: stack-8.2.2.yaml
  steps:
  - bash: |
      git submodule sync
      git submodule update --init
    displayName: Sync submodules
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
    displayName: Install stack
  - bash: |
      source .azure/windows.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/windows.bashrc
      stack --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie`
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE) --test --bench --only-dependencies
      stack install --stack-yaml $(YAML_FILE) # `hie` binary required for tests
      stack exec --stack-yaml $(YAML_FILE) hoogle generate
    displayName: Build Test-dependencies
  - bash: |
      curl -L https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5/z3-4.8.5-x64-win.zip -o /mingw64/z3.zip
      unzip -o /migw64/z3.zip -d /mingw64
    displayName: "Install Runtime Test-Dependencies: z3"
  - bash: |
      source .azure/windows.bashrc
      curl -L https://downloads.haskell.org/cabal/cabal-install-$CABAL_VERSION/cabal-install-$CABAL_VERSION_FULL.zip -o $LOCAL_BIN_PATH/cabal-$CABAL_VERSION.zip
      unzip -o $LOCAL_BIN_PATH/cabal-$CABAL_VERSION.zip -d $LOCAL_BIN_PATH
      cabal v1-update
      stack setup --stack-yaml=stack-8.2.2.yaml
      cabal v1-install liquidhaskell-0.8.2.4 --symlink-bindir=$LOCAL_BIN_PATH -w $(stack path --stack-yaml=stack-8.2.2.yaml --compiler-exe)
    displayName: "Install Runtime Test-Dependencies: liquidhaskell"
  - bash: |
      source .azure/windows.bashrc
      stack test --stack-yaml $(YAML_FILE) :unit-test
    displayName: Run Test
