name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Init git submodules
      run: git submodule update --recursive --init
    - name: Install dependencies
      run: |
        cabal update
        cabal install hoogle
        hoogle generate
    - name: Build
      run: cabal build
#     - name: Run tests
#       run: cabal test
