name: Haskell CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-latest , macOS-latest] # , windows-latest]
        ghc: ['8.6.5', '8.6.4', '8.6.3', '8.6.2', '8.6.1', '8.4.4', '8.4.3', '8.4.2']

    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: recursive
    - uses: bubba/setup-haskell@macos-ghcup
      with:
        ghc-version: ${{matrix.ghc}}
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
        cabal install hoogle
        hoogle generate
    - name: Build
      run: cabal build
#     - name: Run tests
#       run: cabal test
