name: Haskell CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-latest , macOS-latest] # , windows-latest]
        ghc: ['8.6.5', '8.4.4']

    steps:
#     - name: Install ghc and cabal-install
#       if: startsWith(matrix.os, 'macOS')
#       run: brew install ghc cabal-install
    - uses: actions/checkout@v1
      with: 
        submodules: recursive
    - uses: haskell-works/setup-haskell@macos-ghcup
      with:
        ghc-version: ${{matrix.ghc}}
        cabal-version: '3.0'
#       if: startsWith(matrix.os, 'ubuntu')
    - name: Install dependencies
      run: |
        cabal update
        cabal install hoogle
        hoogle generate
    - name: Build
      run: cabal build
#     - name: Run tests
#       run: cabal test
